### ISSUE TITLE
subject matter editor bug on published data

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#838] opened 2021-08-12 18:40 UTC
https://user-images.githubusercontent.com/844306/129250819-15b3b5ed-5225-480e-819e-11b15a292169.mp4

The subject matter entry is blank when you go back into the metadata editor, but the entry is still there on the dandiset landing page

**Comment by satra** [comment] 2021-08-12 22:15
@mvandenburgh - is it possible that the ui is using the schemaVersion from the metadata instead of the infrastructure schema? in that sense 0.4.4 is definitely broken for vjsf.

**Comment by mvandenburgh** [comment] 2021-08-13 13:47
> @mvandenburgh - is it possible that the ui is using the schemaVersion from the metadata instead of the infrastructure schema? in that sense 0.4.4 is definitely broken for vjsf.

No, the UI uses the schema from the infrastructure repo (currently 0.5.1, just double checked it).

**Comment by waxlamp** [comment] 2021-12-29 15:46
I can't reproduce this now, so perhaps it has been fixed. I'm going to close this, but @bendichter if you can still reproduce this please re-open and leave a note.

**Closed by waxlamp** 2021-12-29 15:46 UTC
