### ISSUE TITLE
Can no longer see how big NWB files are before download

### ISSUE THREAD

**Issue by rly** [dandi/dandiarchive#644] opened 2021-04-28 16:17 UTC
![image](https://user-images.githubusercontent.com/310197/116437584-70c08c00-a802-11eb-82d8-395133b0c385.png)

Previously, IIRC, the web interface showed how big each NWB file is. Now it doesn't, so I can no longer select the smallest file to download.

**Comment by satra** [comment] 2021-04-28 17:18
@rly - this is going to be one of our immediate upcoming enhancements. 

from a developer perspective you can look at any dataset quite easily programmatically now.

```python
import requests
url = "https://api.dandiarchive.org/api/dandisets/000026/versions/draft/assets/"
querystring = {"path":"sub-npiI","page_size":"100"}
headers = {"Accept": "application/json"}
resp = requests.request("GET", url, headers=headers, params=querystring).json()
results = resp["results"]
while resp["next"]:
    resp = requests.request("GET", resp["next"], headers=headers).json()
    results.extend(resp["results"])
assert len(results) == resp["count"]
```
and for download links you can use the following:

`https://api.dandiarchive.org/api/dandisets/<dandiid>/versions/draft/assets/<assetuuid>/download/`

the full api is here: https://api.dandiarchive.org/swagger/

and unoffociailly we are testing out this platform: https://dandi.readme.io/reference#getting-started-with-your-api

**Comment by rly** [comment] 2021-04-28 17:22
Great! I'm looking forward to trying out the new API. 

BTW the last link shows me:
![image](https://user-images.githubusercontent.com/310197/116446175-8b4b3300-a80b-11eb-9d5d-17beff39ff6e.png)

**Comment by satra** [comment] 2021-04-28 17:30
learning the ropes - should be active now.

**Comment by yarikoptic** [comment] 2021-04-28 17:39
an alternative is to use `dandi` client (`dandi-cli` repo here), e.g.
```
dandi ls -r -f pyout 'https://gui.dandiarchive.org/#/dandiset/000053'
```
(or `-f yaml` or `-f json` depending your desires).  After https://github.com/dandi/dandi-cli/pull/588 is merged/released (likely later today), you would also get (back) ability to list specific directory by just copy/pasting URL from the browser, i.e. like
```
dandi ls -r -f pyout 'https://gui.dandiarchive.org/#/dandiset/000053/draft/files?location=sub-npI1%2F'
```
PS note -- discovered some issue/interaction in pyout - your original command line might get overridden: https://github.com/pyout/pyout/issues/128

**Comment by yarikoptic** [comment] 2021-05-05 16:33
original issue I think is #586

**Comment by yarikoptic** [comment] 2021-07-19 22:03
let's consider this a duplicate of earlier #586 . Now that API returns sizes for `/paths/` endpoint, fix should be trivial and without extra performance hit

**Closed by yarikoptic** 2021-07-19 22:03 UTC
Labels: UX, girder-feature-parity
