### ISSUE TITLE
Link DANDI Workflow in the UI

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#361] opened 2020-05-28 17:46 UTC
The document to link:

https://docs.google.com/document/d/1ehxd5a6Hurz7VqQDAszEpGASRTUP6muXYwJ5wgXhzU4

**Comment by mgrauer** [comment] 2020-06-03 20:43
Duplicate of #337. Close them both at the same time.

Also, when this gets done, I'd say add the text from https://github.com/dandi/dandiarchive/issues/214 to the `i` icon in the early access message as a tooltip, and that will be enough to close out #214.

**Comment by mgrauer** [comment] 2020-08-13 18:45
Fixed, with a pointer to the handbook.

**Closed by mgrauer** 2020-08-13 18:45 UTC
