### ISSUE TITLE
extra / when delving into path

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#635] opened 2021-04-21 16:35 UTC
also a weird extra `/`
![image](https://user-images.githubusercontent.com/184063/115589020-5f74fe00-a29d-11eb-8259-7ab532ecc047.png)

(also @dchiquito - any particular reason for the api not to return a set of nested objects with minimal info: name, size, download link - if asset)

**Comment by satra** [comment] 2021-04-23 12:25
actually every depth has an extra `/`

![image](https://user-images.githubusercontent.com/184063/115870607-76d2f900-a40d-11eb-98fb-ca641fb9e5d3.png)

**Comment by yarikoptic** [comment] 2021-04-23 12:34
duplicate of #599

**Closed** 2021-04-23 13:07 UTC
Labels: severity-minor, webui
