### ISSUE TITLE
DJANGO_API: getting API key displayed for a newly registered user requires extra click

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#595] opened 2021-03-17 18:14 UTC
earlier today I have registered a `dandibot` user for https://github.com/dandi/dandi-api-webshots/pull/10#issuecomment-801196656 . Registration went smoothly and I was shown to be logged in as `??` in the right corner blue circle.  @jwodder reported some unexpected behavior while trying to use credentials to login for webshots using seleniumin that PR changes. When I clicked on the `??` I saw empty field for `API Key`. 
Then I believe I clicked again on it (but did not catch if once to just disappear or twice to reappear) and "API key" appeared.

**Comment by waxlamp** [comment] 2021-03-29 14:53
I'm not able to reproduce this, perhaps because I did not have to create a completely new user (since I am already logged in to my only GitHub account in this browser).

Do you have a consistent way to trigger this error?

**Comment by yarikoptic** [comment] 2021-03-29 15:37
haven't tried to come up with a consistent recipe.  But may be try in incognito window like I did originally?

**Comment by waxlamp** [comment] 2021-06-18 14:21
I just tried in an incognito window as suggested, and couldn't reproduce. Closing for now but please re-open if you believe there's still a problem.

**Comment by yarikoptic** [comment] 2021-06-18 16:38
did you try to create a new user and login or just as before with an already existing one @waxlamp ?

**Comment by waxlamp** [comment] 2021-06-21 13:36
With an existing user.

I just tried in an incognito window on staging, logging in with Dandibot (which did not yet have an account there), but I could not reproduce the issue. That is, as soon as I logged in, I clicked on the login badge, and saw an API key there.

If this has not caused any difficulty since the initial report, I'd like to close the issue since we cannot reproduce. If you are able to reproduce this reliably, please post instructions in the issue description and then we can leave it open and investigate what's going on.

**Comment by waxlamp** [comment] 2021-12-28 16:45
I tried to repro this again (with Daniel's help--thanks!). We deleted my user from staging and observed what happened w.r.t. the API key display when I was re-added using the normal signup flow, and I could not reproduce.

Details: now, because of the approval workflow, an API key is not displayed for unapproved users by design. As soon as Daniel approved my new user, I refreshed the page and immediately tried to click on the menu to see if I could catch it not displaying the key, but I wasn't able to.

It is possible that an automated script might succeed in opening the menu without seeing the API key listed, but this is a natural consequence of the UI needing to ask the server for the key. I'm going to close this because it doesn't affect human users, and if there's a specific reproducing sequence someone can formulate, we can re-open then.

**Closed by waxlamp** 2021-12-28 16:45 UTC
Labels: UX
