### ISSUE TITLE
add dataset creator automatically to metadata as contact

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#377] opened 2020-06-03 19:55 UTC
this should wait till we have updated schema, but in general we should add the person registering a new dataset as a contributor to the dataset.

**Comment by mgrauer** [comment] 2020-08-03 19:23
Will be closed by #426

**Comment by satra** [comment] 2021-03-29 15:59
@djarecka - it seems like this was never finalized. but would have addressed a bunch of your issues. i'm going to go to the open PR for any further discussion.

**Comment by djarecka** [comment] 2021-03-29 17:26
@satra - ok, so I will ignore the issues for now and will concentrate on dandisets that seed to have everything

**Comment by waxlamp** [comment] 2021-05-12 17:09
#425 is a dupe of this issue, but includes one extra point about also registering the creator as the contact person; closing this in favor of that.

**Closed by waxlamp** 2021-05-12 17:09 UTC
