### ISSUE TITLE
DLP results in errors logged to the console

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#811] opened 2021-07-23 20:20 UTC
go to https://gui.dandiarchive.org/#/dandiset/000029/draft and open console:

![image](https://user-images.githubusercontent.com/39889/126837230-b9a56ff8-bbb4-47ef-94a3-761a3adfdccd.png)

edit: IMHO there should be no errors logged in the console from JS frontend upon "read-only" user operations, even if a dandiset is not entirely kosher for Publish or otherwise defective.  Defects in metadata etc should eventually be communicated via UI somehow.  Also related: #613 but for errors  triggered by user's "non read-only" actions

**Comment by yarikoptic** [comment] 2021-07-23 21:38
FWIW, not specific to 000029 and seems to be present on all dandisets!

**Comment by mvandenburgh** [comment] 2021-07-26 19:49
I believe this is a duplicate of https://github.com/dandi/dandiarchive/issues/772

**Comment by waxlamp** [comment] 2021-07-26 19:55
> I believe this is a duplicate of #772

If you're sure it's the same error, go ahead and close this in favor of #772.

**Comment by mvandenburgh** [comment] 2021-07-28 20:59
> > I believe this is a duplicate of #772
> 
> If you're sure it's the same error, go ahead and close this in favor of #772.

Closing this issue then.

**Closed by mvandenburgh** 2021-07-28 20:59 UTC
Labels: bug
