### ISSUE TITLE
saving metadata JS error

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#712] opened 2021-06-02 18:06 UTC
For dandiset 3, I tried changing Gyorgy Buzsaki's name to György and nothing happened when I pressed the save icon, and when I press the left arrow icon it looks like the change did not save.

I see this in the JS console:

![image](https://user-images.githubusercontent.com/844306/120530520-9ade0e80-c3ab-11eb-9930-af626fe7c105.png)

**Comment by waxlamp** [comment] 2021-06-02 19:04
Ben, are you able to reproduce this? i.e., does this sequence of actions always result in that error on the console?

**Comment by waxlamp** [comment] 2021-06-18 15:59
@bendichter, I see the correct diacritic on György's name; were you able to fix this since filing this issue?

**Comment by bendichter** [comment] 2021-06-18 16:29
yes, I was able to fix this. I don't know what caused the error and am not able to reproduce. I thought the JS error might be helpful, but feel free to close.

**Comment by waxlamp** [comment] 2021-06-21 14:16
I've seen that class of error in a few other circumstances in which the UI allows an action to proceed that, based on permissions, it shouldn't, but I don't think that was specifically connected to the trouble you were running into.

I'll close this issue but of course you can file a new one if this sort of thing crops up again. Thanks Ben!

**Closed by waxlamp** 2021-06-21 14:16 UTC
