### ISSUE TITLE
publish button failing on dandiset 53

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#843] opened 2021-08-15 18:32 UTC
https://user-images.githubusercontent.com/844306/129488742-e396ab78-5ae4-4326-a103-f62bfe2700d5.mp4

**Comment by dchiquito** [comment] 2021-08-16 13:16
The logs suggest this is a problem with `relatedResource` in the metadata:
```
ValueError: identifier has to be from the list:
{'LISSN', 'ISTC', 'arXiv', 'bibcode', 'w3id',               
'LSID', 'URN', 'ISBN', 'PMID', 'ARK', 'IGSN',               
'EAN13', 'PURL', 'DOI', 'Handle', 'URL', 'UPC',             
'ISSN', 'EISSN'}, but https provided   
```
Presumably this shouldn't pass validation, but it obviously has.

**Comment by dchiquito** [comment] 2021-08-16 13:19
https://github.com/dandi/dandischema/blob/92f303e5cc9edeaf1c1369930e37bc203e97f2e0/dandischema/datacite.py#L175-L198 is the problematic code. Looks like it's not equipped to handle an `identifier` with a URL.

**Comment by satra** [comment] 2021-08-16 13:36
@bendichter - one way to handle this is to make the identifier a `doi` as datacite wants it: `DOI:10.1038/s41467-021-20936-8`

@dchiquito -  we indeed should augment the link processing in that section in dandischema knowing that in general identifiers can be urls. @djarecka - do you want to take a stab at this? i.e. the doi code should parse the url to see if it matches some known entity like doi.org and others and then map it to that type or map it to url type.

**Comment by bendichter** [comment] 2021-08-16 13:47
@satra OK, but it's pretty unclear from a user perspective what form to use for the identifiers. The automatic ones in the Asset Summary seem to suggest that we want them as URLs.

![image](https://user-images.githubusercontent.com/844306/129573809-f4d353c8-c67c-4cf3-9f34-8d3e5ffcf4cc.png)

**Comment by satra** [comment] 2021-08-16 14:14
@bendichter - we should allow URLs there, just that the dandischema code needs to be updated. i'm simply suggesting the `DOI:` route as a short term fix, if you would like to have publish work before the code fix is in place.

**Comment by djarecka** [comment] 2021-08-16 17:34
so, the problem is that `attributes["relatedIdentifiers"][i].identifier` could have `url` and we should process it in the same way as in the [elif part](https://github.com/dandi/dandischema/blob/92f303e5cc9edeaf1c1369930e37bc203e97f2e0/dandischema/datacite.py#L189)?

**Comment by satra** [comment] 2021-08-16 18:57
you would then have to parse the url to see if it matches any of the known identifier patterns, if so reduce the url to identifier and proceed. if not, process in the same way as the elif part.

**Comment by bendichter** [comment] 2021-08-19 03:47
This worked for me.

@Saksham20, could you use this work-around for dandiset 54 as well?

**Comment by Saksham20** [comment] 2021-08-19 12:31
Yes, removing the url and suffixing the doi with `DOI` worked on dandiset 54

**Comment by djarecka** [comment] 2021-09-23 13:57
could we close the issue now?

**Comment by waxlamp** [comment] 2021-09-23 14:08
@Saksham20, I'll close this issue, but please reopen if you have any further trouble!

**Closed by waxlamp** 2021-09-23 14:08 UTC
